[project]
name = "wpm-meter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keyboard>=0.13.5",
    "pynput>=1.8.0",
    "pyqt5>=5.15.11",
]
